-- Script para criar as novas tabelas do sistema refatorado

-- Tabela de configuração do estacionamento
CREATE TABLE estacionamento_config (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_vagas NUMBER NOT NULL,
    tarifa_30min NUMBER(10,2),
    tarifa_hora NUMBER(10,2),
    tarifa_diaria NUMBER(10,2),
    tarifa_mensal NUMBER(10,2),
    ativo NUMBER(1) DEFAULT 1 NOT NULL
);

-- Tabela de reservas
CREATE TABLE reserva (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veiculo_id NUMBER NOT NULL,
    vaga VARCHAR2(10) NOT NULL,
    data_reserva TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    data_inicio TIMESTAMP NOT NULL,
    data_fim TIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'ATIVA' NOT NULL,
    CONSTRAINT fk_reserva_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculo(id)
);

-- Adicionar novas colunas na tabela ticket
ALTER TABLE ticket ADD (
    tipo_tarifa VARCHAR2(20) DEFAULT 'HORARIA',
    reserva_id NUMBER
);

-- Adicionar constraint para reserva
ALTER TABLE ticket ADD CONSTRAINT fk_ticket_reserva 
    FOREIGN KEY (reserva_id) REFERENCES reserva(id);

-- Índices para melhor performance
CREATE INDEX ix_reserva_status ON reserva(status);
CREATE INDEX ix_reserva_veiculo ON reserva(veiculo_id);
CREATE INDEX ix_reserva_periodo ON reserva(data_inicio, data_fim);
CREATE INDEX ix_ticket_tipo_tarifa ON ticket(tipo_tarifa);

-- Inserir configuração inicial
INSERT INTO estacionamento_config 
(total_vagas, tarifa_30min, tarifa_hora, tarifa_diaria, tarifa_mensal, ativo) 
VALUES (100, 4.00, 8.00, 30.00, 200.00, 1);

COMMIT;
